# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7e6755b10b6bcd7ad596838b63e2370cd26b858772b4b504ecaaf9e01b40fa4c0a3ff496801d2110d59dba6c644f58baece5e11bdacacea214b565b66df19f

test:
  secret_key_base: 95cc3d5608ff7ebbcf9bf48517875b3778ed87cf77e390a5b6e88f96d39ad12505692af27661d980a098717bd7d80e9cb267dc92d18a458512d7b2b2aaf99bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
